/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.MemHorario;

/**
 *
 * @author ARIAN BEJAR
 */
public class MembresiasPanel extends javax.swing.JPanel {

    /**
     * Creates new form MembresiasPanel
     */
    public MembresiasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMembresias = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnHabilitar = new javax.swing.JButton();
        btnDeshabilitar = new javax.swing.JButton();
        btnHorarios = new javax.swing.JButton();
        inputBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MEMBRESÍAS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 34, 172, 34));

        tbMembresias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Tipo", "Meses", "Días", "Fecha creación", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbMembresias);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 176, 754, 477));

        btnAgregar.setText("Agregar");
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 86, -1, -1));

        btnModificar.setText("Modificar");
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 86, -1, -1));

        btnEliminar.setText("Eliminar");
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 86, -1, -1));

        btnHabilitar.setText("Habilitar");
        add(btnHabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 86, -1, -1));

        btnDeshabilitar.setText("Deshabilitar");
        add(btnDeshabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 86, -1, -1));

        btnHorarios.setText("Horarios");
        add(btnHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 86, -1, -1));
        add(inputBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 140, 30));

        jLabel2.setText("Buscar por nombre :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 136, 120, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnDeshabilitar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnHabilitar;
    public javax.swing.JButton btnHorarios;
    public javax.swing.JButton btnModificar;
    public javax.swing.JTextField inputBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbMembresias;
    // End of variables declaration//GEN-END:variables
}
