/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.MemHorario;

import Style.Estilo;
import java.awt.Color;

/**
 *
 * @author ARIAN BEJAR
 */
public class MembresiasPanel extends javax.swing.JPanel {

    /**
     * Creates new form MembresiasPanel
     */
    public MembresiasPanel() {
        initComponents();
        inicializarEstilo();
    }
    
    private void inicializarEstilo(){
        Estilo.textFieldModerno(inputBuscar);
        Estilo.tablaHeaderModerno(tbMembresias);
        Estilo.botonModerno(btnAgregar,   new Color(33, 150, 243));  // Azul moderno
        Estilo.botonModerno(btnModificar, new Color(255, 152, 0));   // Naranja
        Estilo.botonModerno(btnEliminar,  new Color(244, 67, 54));
        Estilo.botonModerno(btnHabilitar,  new Color(76, 175, 80));
        Estilo.botonModerno(btnDeshabilitar,  new Color(158, 158, 158));
        Estilo.botonModerno(btnHorarios, new Color(0, 184, 148));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMembresias = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnHabilitar = new javax.swing.JButton();
        btnDeshabilitar = new javax.swing.JButton();
        btnHorarios = new javax.swing.JButton();
        inputBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("MEMBRESÍAS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 340, 34));

        tbMembresias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Tipo", "Meses", "Días", "Fecha creación", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbMembresias);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 193, 754, 460));

        btnAgregar.setText("New");
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 70, 40));

        btnModificar.setText("Edit");
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 70, 40));

        btnEliminar.setText("Delete");
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 90, 40));

        btnHabilitar.setText("Habilitar");
        add(btnHabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 110, 40));

        btnDeshabilitar.setText("Deshabilitar");
        add(btnDeshabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 140, 40));

        btnHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clipboard-clock.png"))); // NOI18N
        btnHorarios.setText("Horarios");
        btnHorarios.setIconTextGap(8);
        add(btnHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 170, 40));
        add(inputBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 140, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Buscar por nombre :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inputBuscar1.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 210, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnDeshabilitar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnHabilitar;
    public javax.swing.JButton btnHorarios;
    public javax.swing.JButton btnModificar;
    public javax.swing.JTextField inputBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbMembresias;
    // End of variables declaration//GEN-END:variables
}
