/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.SocioInscripcion;

import Modelo.Membresia;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author ARIAN BEJAR
 */
public class InscripcionView extends javax.swing.JFrame {

    /**
     * Creates new form InscripcionView
     */
    public InscripcionView() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(670, 600); // 👉 dimensiones exactas ancho x alto
        setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/logopequeño.jpg")).getImage());
        this.setTitle("Gestión Gym Esparta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblUsuarios = new javax.swing.JLabel();
        lblUsuarios1 = new javax.swing.JLabel();
        lblUsuarios2 = new javax.swing.JLabel();
        lblUsuarios3 = new javax.swing.JLabel();
        lblUsuarios4 = new javax.swing.JLabel();
        lblUsuarios5 = new javax.swing.JLabel();
        lbDNISocioSelect = new javax.swing.JLabel();
        lbNomSocioSelect = new javax.swing.JLabel();
        lbCorreoSocioSelect = new javax.swing.JLabel();
        lblUsuarios9 = new javax.swing.JLabel();
        lbTipoMem = new javax.swing.JLabel();
        lbMesMem = new javax.swing.JLabel();
        lbDiaMem = new javax.swing.JLabel();
        lblUsuarios13 = new javax.swing.JLabel();
        lblUsuarios14 = new javax.swing.JLabel();
        lbFechaVencimiento = new javax.swing.JLabel();
        lblUsuarios16 = new javax.swing.JLabel();
        lblUsuarios17 = new javax.swing.JLabel();
        cbOpcionMembresias = new javax.swing.JComboBox<>();
        lblUsuarios18 = new javax.swing.JLabel();
        dateChoComienzo = new com.toedter.calendar.JDateChooser();
        btnAgregarIns = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInscripciones = new javax.swing.JTable();
        btnPagoMem = new javax.swing.JButton();
        btnEliminarIns = new javax.swing.JButton();
        lbMontoMem = new javax.swing.JLabel();
        lblUsuarios19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 197, 655, 10));

        lblUsuarios.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios.setText("INSCRIPCIÓN");
        getContentPane().add(lblUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 6, -1, -1));

        lblUsuarios1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblUsuarios1.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios1.setText("Membresía");
        getContentPane().add(lblUsuarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 213, -1, -1));

        lblUsuarios2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblUsuarios2.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios2.setText("Socio");
        getContentPane().add(lblUsuarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 55, -1, -1));

        lblUsuarios3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios3.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios3.setText("DNI:");
        getContentPane().add(lblUsuarios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 90, -1, -1));

        lblUsuarios4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios4.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios4.setText("Nombre:");
        getContentPane().add(lblUsuarios4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 121, -1, -1));

        lblUsuarios5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios5.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios5.setText("Correo:");
        getContentPane().add(lblUsuarios5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 152, -1, -1));

        lbDNISocioSelect.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbDNISocioSelect.setForeground(new java.awt.Color(0, 0, 0));
        lbDNISocioSelect.setText("---------");
        getContentPane().add(lbDNISocioSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 90, 274, -1));

        lbNomSocioSelect.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbNomSocioSelect.setForeground(new java.awt.Color(0, 0, 0));
        lbNomSocioSelect.setText("---------");
        getContentPane().add(lbNomSocioSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 121, 274, -1));

        lbCorreoSocioSelect.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbCorreoSocioSelect.setForeground(new java.awt.Color(0, 0, 0));
        lbCorreoSocioSelect.setText("---------");
        getContentPane().add(lbCorreoSocioSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 152, 274, -1));

        lblUsuarios9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios9.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios9.setText("Días");
        getContentPane().add(lblUsuarios9, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 364, -1, -1));

        lbTipoMem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbTipoMem.setForeground(new java.awt.Color(0, 0, 0));
        lbTipoMem.setText("----");
        getContentPane().add(lbTipoMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 302, 104, -1));

        lbMesMem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbMesMem.setForeground(new java.awt.Color(0, 0, 0));
        lbMesMem.setText("----");
        getContentPane().add(lbMesMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 333, 104, -1));

        lbDiaMem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbDiaMem.setForeground(new java.awt.Color(0, 0, 0));
        lbDiaMem.setText("----");
        getContentPane().add(lbDiaMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 364, 104, -1));

        lblUsuarios13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios13.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios13.setText("Tipo:");
        getContentPane().add(lblUsuarios13, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 302, -1, -1));

        lblUsuarios14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios14.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios14.setText("Meses:");
        getContentPane().add(lblUsuarios14, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 333, -1, -1));

        lbFechaVencimiento.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbFechaVencimiento.setForeground(new java.awt.Color(0, 0, 0));
        lbFechaVencimiento.setText("----");
        getContentPane().add(lbFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 302, 95, -1));

        lblUsuarios16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios16.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios16.setText("Vencimiento");
        getContentPane().add(lblUsuarios16, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 302, -1, -1));

        lblUsuarios17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios17.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios17.setText("Membresía");
        getContentPane().add(lblUsuarios17, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 257, -1, -1));

        getContentPane().add(cbOpcionMembresias, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 254, 104, -1));

        lblUsuarios18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios18.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios18.setText("Comienza");
        getContentPane().add(lblUsuarios18, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 257, -1, -1));
        getContentPane().add(dateChoComienzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 254, 145, -1));

        btnAgregarIns.setText("Agregar inscripción");
        getContentPane().add(btnAgregarIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 174, 35));

        tbInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID ", "Fecha comienzo", "Fecha vencimiento", "Membresía", "Precio", "Fecha creación", "Estado inscripcion", "Estado pago"
            }
        ));
        jScrollPane1.setViewportView(tbInscripciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 435, 655, 165));

        btnPagoMem.setText("Pago membresía");
        getContentPane().add(btnPagoMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 399, 146, 30));

        btnEliminarIns.setText("Eliminar inscripcion");
        getContentPane().add(btnEliminarIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 399, 149, 30));

        lbMontoMem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbMontoMem.setForeground(new java.awt.Color(0, 0, 0));
        lbMontoMem.setText("----");
        getContentPane().add(lbMontoMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 333, 94, -1));

        lblUsuarios19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios19.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios19.setText("Precio");
        getContentPane().add(lblUsuarios19, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 333, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscripcionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscripcionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscripcionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscripcionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscripcionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarIns;
    public javax.swing.JButton btnEliminarIns;
    public javax.swing.JButton btnPagoMem;
    public javax.swing.JComboBox<Membresia> cbOpcionMembresias;
    public com.toedter.calendar.JDateChooser dateChoComienzo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lbCorreoSocioSelect;
    public javax.swing.JLabel lbDNISocioSelect;
    public javax.swing.JLabel lbDiaMem;
    public javax.swing.JLabel lbFechaVencimiento;
    public javax.swing.JLabel lbMesMem;
    public javax.swing.JLabel lbMontoMem;
    public javax.swing.JLabel lbNomSocioSelect;
    public javax.swing.JLabel lbTipoMem;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblUsuarios1;
    private javax.swing.JLabel lblUsuarios13;
    private javax.swing.JLabel lblUsuarios14;
    private javax.swing.JLabel lblUsuarios16;
    private javax.swing.JLabel lblUsuarios17;
    private javax.swing.JLabel lblUsuarios18;
    private javax.swing.JLabel lblUsuarios19;
    private javax.swing.JLabel lblUsuarios2;
    private javax.swing.JLabel lblUsuarios3;
    private javax.swing.JLabel lblUsuarios4;
    private javax.swing.JLabel lblUsuarios5;
    private javax.swing.JLabel lblUsuarios9;
    public javax.swing.JTable tbInscripciones;
    // End of variables declaration//GEN-END:variables
}
