/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.SocioInscripcion;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author ARIAN BEJAR
 */
public class PagoInscripcionView extends javax.swing.JDialog {

    /**
     * Creates new form PagoInscripcionView
     */
    public PagoInscripcionView(JFrame parent) {
    super(parent, "Pago de Inscripción", true); // true = modal
    initComponents();
    setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    setSize(465, 600);
    setResizable(false);
    setLocationRelativeTo(parent);
    setIconImage(new ImageIcon(getClass().getResource("/Images/logopequeño.jpg")).getImage());
    setTitle("Gestión Gym Esparta");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPagos = new javax.swing.JTable();
        lblUsuarios = new javax.swing.JLabel();
        lblUsuarios2 = new javax.swing.JLabel();
        lblUsuarios3 = new javax.swing.JLabel();
        lblUsuarios4 = new javax.swing.JLabel();
        lblUsuarios5 = new javax.swing.JLabel();
        lbMontoPagado = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lbMostrarPago = new javax.swing.JLabel();
        lblUsuarios10 = new javax.swing.JLabel();
        lblUsuarios11 = new javax.swing.JLabel();
        inputImporte = new javax.swing.JTextField();
        cbOpcionTipoPago = new javax.swing.JComboBox<>();
        btnAnularPago = new javax.swing.JButton();
        btnAgregarPago = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Importe ", "Fecha Pago", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbPagos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 371, 450, 230));

        lblUsuarios.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios.setText("REALIZAR PAGO");
        getContentPane().add(lblUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 6, -1, -1));

        lblUsuarios2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblUsuarios2.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios2.setText("Datos de membresía");
        getContentPane().add(lblUsuarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 49, -1, -1));

        lblUsuarios3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios3.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios3.setText("Fecha:");
        getContentPane().add(lblUsuarios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 84, -1, -1));

        lblUsuarios4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios4.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios4.setText("Precio");
        getContentPane().add(lblUsuarios4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 115, -1, -1));

        lblUsuarios5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios5.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios5.setText("Total pagado:");
        getContentPane().add(lblUsuarios5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 146, -1, -1));

        lbMontoPagado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbMontoPagado.setForeground(new java.awt.Color(0, 0, 0));
        lbMontoPagado.setText("----");
        getContentPane().add(lbMontoPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 146, 112, -1));

        lbPrecio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lbPrecio.setText("----");
        getContentPane().add(lbPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 111, 112, -1));

        lbFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(0, 0, 0));
        lbFecha.setText("----");
        getContentPane().add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 80, 112, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 177, 450, 10));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMostrarPago.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbMostrarPago.setForeground(new java.awt.Color(0, 0, 0));
        lbMostrarPago.setText("Sin pagar");
        jPanel1.add(lbMostrarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 33));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 180, 90));

        lblUsuarios10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios10.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios10.setText("Importe");
        getContentPane().add(lblUsuarios10, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 201, -1, -1));

        lblUsuarios11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsuarios11.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios11.setText("Tipo de pago");
        getContentPane().add(lblUsuarios11, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 244, -1, -1));
        getContentPane().add(inputImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 199, 263, -1));

        cbOpcionTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta de crédito", "Tarjeta de débito", "Transferencia bancaria", "Yape / Plin / Billetera digital" }));
        getContentPane().add(cbOpcionTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 241, 265, -1));

        btnAnularPago.setText("Anular pago");
        getContentPane().add(btnAnularPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 335, 121, 30));

        btnAgregarPago.setText("Agregar pago");
        getContentPane().add(btnAgregarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 273, 130, 32));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 311, 450, 7));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoInscripcionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoInscripcionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoInscripcionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoInscripcionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarPago;
    public javax.swing.JButton btnAnularPago;
    public javax.swing.JComboBox<String> cbOpcionTipoPago;
    public javax.swing.JTextField inputImporte;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel lbFecha;
    public javax.swing.JLabel lbMontoPagado;
    public javax.swing.JLabel lbMostrarPago;
    public javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblUsuarios10;
    private javax.swing.JLabel lblUsuarios11;
    private javax.swing.JLabel lblUsuarios2;
    private javax.swing.JLabel lblUsuarios3;
    private javax.swing.JLabel lblUsuarios4;
    private javax.swing.JLabel lblUsuarios5;
    public javax.swing.JTable tbPagos;
    // End of variables declaration//GEN-END:variables
}
