/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Usuario;
import Modelo.UsuarioDAO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ARIAN BEJAR
 */
public class RegistrarUserView extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarUserView
     */
    public RegistrarUserView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/logopequeño.jpg")).getImage());
        this.setTitle("Gestión Gym Esparta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPassRegister = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombreRegister = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtApeRegister = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtDniRegister = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtUserRegister = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        volverRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 475));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        btnRegister.setBackground(new java.awt.Color(93, 29, 30));
        btnRegister.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Registrar");
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 310, 60));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 84, 31));

        txtPassRegister.setBackground(new java.awt.Color(245, 245, 245));
        txtPassRegister.setForeground(new java.awt.Color(0, 0, 0));
        txtPassRegister.setBorder(null);
        jPanel1.add(txtPassRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 310, 36));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("DNI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Apellidos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(93, 29, 30));
        jSeparator1.setForeground(new java.awt.Color(93, 29, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 310, 30));

        txtNombreRegister.setBackground(new java.awt.Color(245, 245, 245));
        txtNombreRegister.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreRegister.setBorder(null);
        jPanel1.add(txtNombreRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 310, 30));

        jSeparator2.setBackground(new java.awt.Color(93, 29, 30));
        jSeparator2.setForeground(new java.awt.Color(93, 29, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 310, 30));

        txtApeRegister.setBackground(new java.awt.Color(245, 245, 245));
        txtApeRegister.setForeground(new java.awt.Color(0, 0, 0));
        txtApeRegister.setBorder(null);
        jPanel1.add(txtApeRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 310, 36));

        jSeparator3.setBackground(new java.awt.Color(93, 29, 30));
        jSeparator3.setForeground(new java.awt.Color(93, 29, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 310, 30));

        txtDniRegister.setBackground(new java.awt.Color(245, 245, 245));
        txtDniRegister.setForeground(new java.awt.Color(0, 0, 0));
        txtDniRegister.setBorder(null);
        jPanel1.add(txtDniRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 310, 36));

        jSeparator4.setBackground(new java.awt.Color(93, 29, 30));
        jSeparator4.setForeground(new java.awt.Color(93, 29, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 310, 10));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Usuario");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        txtUserRegister.setBackground(new java.awt.Color(245, 245, 245));
        txtUserRegister.setForeground(new java.awt.Color(0, 0, 0));
        txtUserRegister.setBorder(null);
        jPanel1.add(txtUserRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 310, 36));

        jSeparator5.setBackground(new java.awt.Color(93, 29, 30));
        jSeparator5.setForeground(new java.awt.Color(93, 29, 30));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 10, 280));

        volverRegister.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        volverRegister.setText("X");
        jPanel1.add(volverRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 46, 49));

        jLabel5.setBackground(new java.awt.Color(93, 29, 30));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(93, 29, 30));
        jLabel5.setText("REGISTER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(93, 29, 30));
        jSeparator6.setForeground(new java.awt.Color(93, 29, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 310, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void limpiar(){
        txtUserRegister.setText("");
        txtPassRegister.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JTextField txtApeRegister;
    public javax.swing.JTextField txtDniRegister;
    public javax.swing.JTextField txtNombreRegister;
    public javax.swing.JTextField txtPassRegister;
    public javax.swing.JTextField txtUserRegister;
    public javax.swing.JButton volverRegister;
    // End of variables declaration//GEN-END:variables
}
